[package]
name = "pass"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
console = "0.15.8"
rusqlite = "0.31.0"
sqlx = { version = "0.7", features = [ "runtime-async-std" ] }
